---
- name: systemd_resolved | Checking If systemd-resolved Service Is Present # noqa command-instead-of-module
  ansible.builtin.command: systemctl status systemd-resolved.service
  register: _dnsmasq_systemd_resolved_check
  changed_when: false
  failed_when: false

- name: systemd_resolved | Disabling and Stopping systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true
  register: _dnsmasq_systemd_resolved_disabled
  notify:
    - restart dnsmasq
  when: _dnsmasq_systemd_resolved_check['rc'] == 0

- name: systemd_resolved | Checking If /etc/resolv.conf Exists
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: _dnsmasq_resolv_conf

- name: systemd_resolved | Removing Existing /etc/resolv.conf If symlink # noqa no-handler
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true
  register: _dnsmasq_resolv_conf_removed
  when:
    - _dnsmasq_systemd_resolved_disabled['changed']
    - _dnsmasq_resolv_conf['stat']['islnk']

- name: systemd_resolved | Creating /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: o=rw,g=r,o=r
  become: true
  notify:
    - restart dnsmasq
  when: ansible_virtualization_type != "docker"

- name: systemd | Check if running Ubuntu 24.04+
  ansible.builtin.set_fact:
    is_ubuntu_24_or_later: "{{ ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '>=') }}"

- name: systemd | Configure dnsmasq service for Ubuntu 24.04+
  block:
    - name: systemd | Ensure dnsmasq drop-in directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/dnsmasq.service.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: systemd | Disable resolvconf integration for dnsmasq
      ansible.builtin.copy:
        dest: /etc/systemd/system/dnsmasq.service.d/override.conf
        content: |
          [Service]
          ExecStartPost=
          ExecStop=
        owner: root
        group: root
        mode: '0644'
      notify:
        - reload systemd
        - restart dnsmasq
  when: is_ubuntu_24_or_later