---
# handlers file for ansible-dnsmasq
- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true